// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "nathan.lu",
            "url": "https://tedmax100.github.io/"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/confirm-forget-password": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "忘記密碼認證碼 API",
                "parameters": [
                    {
                        "description": "paramters",
                        "name": "{array}",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/requests_atuh.ConfirmForgotPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功回傳值",
                        "schema": {
                            "$ref": "#/definitions/facades.ResponseSuccess"
                        }
                    }
                }
            }
        },
        "/confirmation-code": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "註冊認證碼 API",
                "parameters": [
                    {
                        "description": "paramters",
                        "name": "{array}",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/requests_atuh.ConfirmationCode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功回傳值",
                        "schema": {
                            "$ref": "#/definitions/facades.ResponseSuccess"
                        }
                    }
                }
            }
        },
        "/forget-password": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "忘記密碼 API",
                "parameters": [
                    {
                        "description": "paramters",
                        "name": "{array}",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/requests_atuh.ForgotPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功回傳值",
                        "schema": {
                            "$ref": "#/definitions/facades.ResponseSuccess"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "登入 API",
                "parameters": [
                    {
                        "description": "paramters",
                        "name": "{array}",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/requests_atuh.AuthLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功回傳值",
                        "schema": {
                            "$ref": "#/definitions/responses.ResponseLogin"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "註冊 API",
                "parameters": [
                    {
                        "description": "paramters",
                        "name": "{array}",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/requests_atuh.UserRegister"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功回傳值",
                        "schema": {
                            "$ref": "#/definitions/facades.ResponseSuccess"
                        }
                    }
                }
            }
        },
        "/trans-access-code": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Access Code 轉換為 Access Token API",
                "parameters": [
                    {
                        "description": "paramters",
                        "name": "{array}",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/requests_atuh.TransAccessCode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功回傳值",
                        "schema": {
                            "$ref": "#/definitions/facades.ResponseSuccess"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "facades.ResponseSuccess": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "requests_atuh.AuthLogin": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "test@gmail.com"
                },
                "password": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "testPassword"
                }
            }
        },
        "requests_atuh.ConfirmForgotPassword": {
            "type": "object",
            "required": [
                "confirmation_code",
                "user"
            ],
            "properties": {
                "confirmation_code": {
                    "type": "string",
                    "example": "123456"
                },
                "user": {
                    "$ref": "#/definitions/requests_atuh.User"
                }
            }
        },
        "requests_atuh.ConfirmationCode": {
            "type": "object",
            "properties": {
                "confirmation_code": {
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "test@gmail.com"
                }
            }
        },
        "requests_atuh.ForgotPassword": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string",
                    "example": "test@gmail.com"
                }
            }
        },
        "requests_atuh.TransAccessCode": {
            "type": "object",
            "properties": {
                "access_code": {
                    "type": "string",
                    "example": "abcde-fgh-ijk-lmn"
                }
            }
        },
        "requests_atuh.User": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "Password is the password decided by the user\nat signup time. This field is required and no signup\ncan work without this.\nTo create a secure password, contraints on this field are\nit must contain an uppercase and lowercase letter,\na special symbol and a number.",
                    "type": "string",
                    "example": "testPassword"
                },
                "username": {
                    "description": "Username is the username decided by the user\nat signup time. This field is not required but it could\nbe useful to have",
                    "type": "string",
                    "example": "test@gmail.com"
                }
            }
        },
        "requests_atuh.UserRegister": {
            "type": "object",
            "required": [
                "email",
                "user"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "test@gmail.com"
                },
                "user": {
                    "$ref": "#/definitions/requests_atuh.User"
                }
            }
        },
        "responses.AuthenticationResult": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string",
                    "example": "eyJxxxxxxx"
                },
                "expiresIn": {
                    "type": "integer",
                    "example": 3600
                },
                "idToken": {
                    "type": "string",
                    "example": "eyJxxxxxxx"
                },
                "newDeviceMetadata": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string",
                    "example": "eyJxxxxxxx"
                },
                "tokenType": {
                    "type": "string",
                    "example": "bearer"
                }
            }
        },
        "responses.ResponseLogin": {
            "type": "object",
            "properties": {
                "authenticationResult": {
                    "$ref": "#/definitions/responses.AuthenticationResult"
                },
                "challengeName": {
                    "type": "string"
                },
                "session": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8008",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Gin swagger",
	Description:      "Gin swagger",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
